<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="26" total="81" passed="37" failed="18" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-17T17:10:48 AMT" name="IQsoft API Integration" finished-at="2022-10-17T17:12:15 AMT" duration-ms="87529">
    <groups>
    </groups>
    <test started-at="2022-10-17T17:10:48 AMT" name="API Integration Automation Test" finished-at="2022-10-17T17:12:15 AMT" duration-ms="87529">
      <class name="testCases.IqSoft_API_1_OpenGame_Positive_Test">
        <test-method is-config="true" signature="setupSuite()[pri:0, instance:testCases.IqSoft_API_1_OpenGame_Positive_Test@1c5920df]" started-at="2022-10-17T17:10:48 AMT" name="setupSuite" finished-at="2022-10-17T17:10:48 AMT" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method is-config="true" signature="setUpTestCase()[pri:0, instance:testCases.IqSoft_API_1_OpenGame_Positive_Test@1c5920df]" started-at="2022-10-17T17:10:48 AMT" name="setUpTestCase" finished-at="2022-10-17T17:10:50 AMT" duration-ms="1853" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method signature="OpenGameAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_1_OpenGame_Positive_Test@1c5920df]" started-at="2022-10-17T17:10:50 AMT" name="OpenGameAPIValidateStatusCod" finished-at="2022-10-17T17:10:50 AMT" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidateStatusCod -->
        <test-method signature="OpenGameAPIValidatePositiveResponse()[pri:3, instance:testCases.IqSoft_API_1_OpenGame_Positive_Test@1c5920df]" started-at="2022-10-17T17:10:50 AMT" name="OpenGameAPIValidatePositiveResponse" finished-at="2022-10-17T17:10:50 AMT" depends-on-methods="testCases.IqSoft_API_1_OpenGame_Positive_Test.OpenGameAPIValidateStatusCod" duration-ms="13" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
ResponseObject: null did not expect [null] but found [null],
ResponseObject Don't Contain http:// expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
ResponseObject: null did not expect [null] but found [null],
ResponseObject Don't Contain http:// expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_1_OpenGame_Positive_Test.OpenGameAPIValidatePositiveResponse(IqSoft_API_1_OpenGame_Positive_Test.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidatePositiveResponse -->
        <test-method is-config="true" signature="tearDownSuite()[pri:0, instance:testCases.IqSoft_API_1_OpenGame_Positive_Test@1c5920df]" started-at="2022-10-17T17:12:16 AMT" name="tearDownSuite" finished-at="2022-10-17T17:12:16 AMT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- testCases.IqSoft_API_1_OpenGame_Positive_Test -->
      <class name="testCases.IqSoft_API_1_OpenGame_Negative_Test">
        <test-method signature="OpenGameAPIValidateResponseWithInvalidToken()[pri:1, instance:testCases.IqSoft_API_1_OpenGame_Negative_Test@7f485fda]" started-at="2022-10-17T17:10:50 AMT" name="OpenGameAPIValidateResponseWithInvalidToken" finished-at="2022-10-17T17:10:51 AMT" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidateResponseWithInvalidToken -->
        <test-method signature="OpenGameAPIValidateResponseWithExpiredToken()[pri:2, instance:testCases.IqSoft_API_1_OpenGame_Negative_Test@7f485fda]" started-at="2022-10-17T17:10:51 AMT" name="OpenGameAPIValidateResponseWithExpiredToken" finished-at="2022-10-17T17:10:51 AMT" duration-ms="625" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_1_OpenGame_Negative_Test.OpenGameAPIValidateResponseWithExpiredToken(IqSoft_API_1_OpenGame_Negative_Test.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidateResponseWithExpiredToken -->
        <test-method signature="OpenGameAPIValidateResponseWithInvalidPartnerID()[pri:3, instance:testCases.IqSoft_API_1_OpenGame_Negative_Test@7f485fda]" started-at="2022-10-17T17:10:51 AMT" name="OpenGameAPIValidateResponseWithInvalidPartnerID" finished-at="2022-10-17T17:10:52 AMT" duration-ms="653" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_1_OpenGame_Negative_Test.OpenGameAPIValidateResponseWithInvalidPartnerID(IqSoft_API_1_OpenGame_Negative_Test.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidateResponseWithInvalidPartnerID -->
        <test-method signature="OpenGameAPIValidateResponseWithInvalidGameID()[pri:4, instance:testCases.IqSoft_API_1_OpenGame_Negative_Test@7f485fda]" started-at="2022-10-17T17:10:52 AMT" name="OpenGameAPIValidateResponseWithInvalidGameID" finished-at="2022-10-17T17:10:52 AMT" duration-ms="520" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidateResponseWithInvalidGameID -->
        <test-method signature="OpenGameAPIValidateResponseWithInvalidDomain()[pri:5, instance:testCases.IqSoft_API_1_OpenGame_Negative_Test@7f485fda]" started-at="2022-10-17T17:10:52 AMT" name="OpenGameAPIValidateResponseWithInvalidDomain" finished-at="2022-10-17T17:10:53 AMT" duration-ms="668" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 21 expected [43] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [43] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_1_OpenGame_Negative_Test.OpenGameAPIValidateResponseWithInvalidDomain(IqSoft_API_1_OpenGame_Negative_Test.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenGameAPIValidateResponseWithInvalidDomain -->
      </class> <!-- testCases.IqSoft_API_1_OpenGame_Negative_Test -->
      <class name="testCases.IqSoft_API_3_GetBalance_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_3_GetBalance_Positive_Test@d737b89]" started-at="2022-10-17T17:10:54 AMT" name="setUp" finished-at="2022-10-17T17:10:54 AMT" duration-ms="595" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="GetBalanceAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_3_GetBalance_Positive_Test@d737b89]" started-at="2022-10-17T17:10:54 AMT" name="GetBalanceAPIValidateStatusCod" finished-at="2022-10-17T17:10:54 AMT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetBalanceAPIValidateStatusCod -->
        <test-method signature="GetBalanceAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_3_GetBalance_Positive_Test@d737b89]" started-at="2022-10-17T17:10:54 AMT" name="GetBalanceAPIValidatePositiveResponse" finished-at="2022-10-17T17:10:54 AMT" depends-on-methods="testCases.IqSoft_API_3_GetBalance_Positive_Test.GetBalanceAPIValidateStatusCod" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetBalanceAPIValidatePositiveResponse -->
      </class> <!-- testCases.IqSoft_API_3_GetBalance_Positive_Test -->
      <class name="testCases.IqSoft_API_6_RollBack_Negative_Test">
        <test-method signature="RollBackAPIValidateResponseWithInvalidToken()[pri:1, instance:testCases.IqSoft_API_6_RollBack_Negative_Test@909217e]" started-at="2022-10-17T17:12:02 AMT" name="RollBackAPIValidateResponseWithInvalidToken" finished-at="2022-10-17T17:12:04 AMT" duration-ms="2325" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
amountAfterRollBack: 9480.7 = amountAfterCredit: 9479.7 expected [9479.7] but found [9480.7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack: 9480.7 = amountAfterCredit: 9479.7 expected [9479.7] but found [9480.7]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseWithInvalidToken(IqSoft_API_6_RollBack_Negative_Test.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateResponseWithInvalidToken -->
        <test-method signature="RollBackAPIValidateResponseUsingInvalidProductID()[pri:2, instance:testCases.IqSoft_API_6_RollBack_Negative_Test@909217e]" started-at="2022-10-17T17:12:04 AMT" name="RollBackAPIValidateResponseUsingInvalidProductID" finished-at="2022-10-17T17:12:06 AMT" duration-ms="2225" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
amountAfterRollBack : 9480.7 = amountAfterCredit: 9479.7 expected [9479.7] but found [9480.7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack : 9480.7 = amountAfterCredit: 9479.7 expected [9479.7] but found [9480.7]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingInvalidProductID(IqSoft_API_6_RollBack_Negative_Test.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateResponseUsingInvalidProductID -->
        <test-method signature="RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit()[pri:3, instance:testCases.IqSoft_API_6_RollBack_Negative_Test@909217e]" started-at="2022-10-17T17:12:06 AMT" name="RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit" finished-at="2022-10-17T17:12:08 AMT" duration-ms="1429" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit -->
        <test-method signature="RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice()[pri:4, instance:testCases.IqSoft_API_6_RollBack_Negative_Test@909217e]" started-at="2022-10-17T17:12:08 AMT" name="RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice" finished-at="2022-10-17T17:12:11 AMT" duration-ms="3484" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
amountAfterRollBack2 : 9481.7 = amountAfterRollBack1: 9480.7 expected [9480.7] but found [9481.7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack2 : 9481.7 = amountAfterRollBack1: 9480.7 expected [9480.7] but found [9481.7]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice(IqSoft_API_6_RollBack_Negative_Test.java:218)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice -->
        <test-method signature="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice()[pri:5, instance:testCases.IqSoft_API_6_RollBack_Negative_Test@909217e]" started-at="2022-10-17T17:12:11 AMT" name="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice" finished-at="2022-10-17T17:12:15 AMT" duration-ms="4383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice -->
      </class> <!-- testCases.IqSoft_API_6_RollBack_Negative_Test -->
      <class name="testCases.IqSoft_API_5_Debit_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_5_Debit_Positive_Test@35dab4eb]" started-at="2022-10-17T17:10:56 AMT" name="setUp" finished-at="2022-10-17T17:10:58 AMT" duration-ms="1801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="DebitAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_5_Debit_Positive_Test@35dab4eb]" started-at="2022-10-17T17:10:58 AMT" name="DebitAPIValidateStatusCod" finished-at="2022-10-17T17:10:58 AMT" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateStatusCod -->
        <test-method signature="DebitAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_5_Debit_Positive_Test@35dab4eb]" started-at="2022-10-17T17:10:58 AMT" name="DebitAPIValidatePositiveResponse" finished-at="2022-10-17T17:10:58 AMT" depends-on-methods="testCases.IqSoft_API_5_Debit_Positive_Test.DebitAPIValidateStatusCod" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidatePositiveResponse -->
      </class> <!-- testCases.IqSoft_API_5_Debit_Positive_Test -->
      <class name="testCases.IqSoft_API_2_Authorization_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_2_Authorization_Positive_Test@28261e8e]" started-at="2022-10-17T17:10:53 AMT" name="setUp" finished-at="2022-10-17T17:10:54 AMT" duration-ms="758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="AuthorizationAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_2_Authorization_Positive_Test@28261e8e]" started-at="2022-10-17T17:10:54 AMT" name="AuthorizationAPIValidateStatusCod" finished-at="2022-10-17T17:10:54 AMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AuthorizationAPIValidateStatusCod -->
        <test-method signature="AuthorizationAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_2_Authorization_Positive_Test@28261e8e]" started-at="2022-10-17T17:10:54 AMT" name="AuthorizationAPIValidatePositiveResponse" finished-at="2022-10-17T17:10:54 AMT" depends-on-methods="testCases.IqSoft_API_2_Authorization_Positive_Test.AuthorizationAPIValidateStatusCod" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AuthorizationAPIValidatePositiveResponse -->
      </class> <!-- testCases.IqSoft_API_2_Authorization_Positive_Test -->
      <class name="testCases.IqSoft_API_2_Authorization_Negative_Test">
        <test-method signature="AuthorizationAPIValidateResponseWithExpiredToken()[pri:1, instance:testCases.IqSoft_API_2_Authorization_Negative_Test@5f049ea1]" started-at="2022-10-17T17:11:10 AMT" name="AuthorizationAPIValidateResponseWithExpiredToken" finished-at="2022-10-17T17:11:11 AMT" duration-ms="1239" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithExpiredToken(IqSoft_API_2_Authorization_Negative_Test.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AuthorizationAPIValidateResponseWithExpiredToken -->
        <test-method signature="AuthorizationAPIValidateResponseWithInvalidToken()[pri:2, instance:testCases.IqSoft_API_2_Authorization_Negative_Test@5f049ea1]" started-at="2022-10-17T17:11:11 AMT" name="AuthorizationAPIValidateResponseWithInvalidToken" finished-at="2022-10-17T17:11:12 AMT" duration-ms="815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AuthorizationAPIValidateResponseWithInvalidToken -->
        <test-method signature="AuthorizationAPIValidateResponseWithInvalidProductID()[pri:3, instance:testCases.IqSoft_API_2_Authorization_Negative_Test@5f049ea1]" started-at="2022-10-17T17:11:12 AMT" name="AuthorizationAPIValidateResponseWithInvalidProductID" finished-at="2022-10-17T17:11:12 AMT" duration-ms="620" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description: null expected [ProductNotFound] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description: null expected [ProductNotFound] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidProductID(IqSoft_API_2_Authorization_Negative_Test.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AuthorizationAPIValidateResponseWithInvalidProductID -->
      </class> <!-- testCases.IqSoft_API_2_Authorization_Negative_Test -->
      <class name="testCases.IqSoft_API_5_Debit_Negative_Test">
        <test-method signature="DebitAPIValidateResponseWithInvalidToken()[pri:1, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:37 AMT" name="DebitAPIValidateResponseWithInvalidToken" finished-at="2022-10-17T17:11:40 AMT" duration-ms="3039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseWithInvalidToken -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidProductID()[pri:2, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:40 AMT" name="DebitAPIValidateResponseUsingInvalidProductID" finished-at="2022-10-17T17:11:43 AMT" duration-ms="3471" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidProductID(IqSoft_API_5_Debit_Negative_Test.java:120)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidProductID -->
        <test-method signature="DebitAPIValidateResponseUsingTransactionIDTwice()[pri:3, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:43 AMT" name="DebitAPIValidateResponseUsingTransactionIDTwice" finished-at="2022-10-17T17:11:48 AMT" duration-ms="4602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingTransactionIDTwice -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidCreditTransactionID()[pri:4, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:48 AMT" name="DebitAPIValidateResponseUsingInvalidCreditTransactionID" finished-at="2022-10-17T17:11:49 AMT" duration-ms="1497" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [50] but found [0],
Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
amountAfterDebit: 9485.7 = amountBeforeDebit: 9480.7 expected [9480.7] but found [9485.7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [50] but found [0],
Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
amountAfterDebit: 9485.7 = amountBeforeDebit: 9480.7 expected [9480.7] but found [9485.7]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidCreditTransactionID(IqSoft_API_5_Debit_Negative_Test.java:230)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidCreditTransactionID -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidAmount(java.lang.Double)[pri:5, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:49 AMT" name="DebitAPIValidateResponseUsingInvalidAmount" data-provider="invalidAmount" finished-at="2022-10-17T17:11:52 AMT" duration-ms="2698" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[0.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:279)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidAmount(java.lang.Double)[pri:5, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:52 AMT" name="DebitAPIValidateResponseUsingInvalidAmount" data-provider="invalidAmount" finished-at="2022-10-17T17:11:55 AMT" duration-ms="2501" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidAmount(java.lang.Double)[pri:5, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:55 AMT" name="DebitAPIValidateResponseUsingInvalidAmount" data-provider="invalidAmount" finished-at="2022-10-17T17:11:57 AMT" duration-ms="2443" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidAmount(java.lang.Double)[pri:5, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:57 AMT" name="DebitAPIValidateResponseUsingInvalidAmount" data-provider="invalidAmount" finished-at="2022-10-17T17:11:59 AMT" duration-ms="2287" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.05]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
        <test-method signature="DebitAPIValidateResponseUsingInvalidAmount(java.lang.Double)[pri:5, instance:testCases.IqSoft_API_5_Debit_Negative_Test@72035809]" started-at="2022-10-17T17:11:59 AMT" name="DebitAPIValidateResponseUsingInvalidAmount" data-provider="invalidAmount" finished-at="2022-10-17T17:12:02 AMT" duration-ms="2330" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.005]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
      </class> <!-- testCases.IqSoft_API_5_Debit_Negative_Test -->
      <class name="testCases.IqSoft_API_4_Credit_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_4_Credit_Positive_Test@8519cb4]" started-at="2022-10-17T17:10:54 AMT" name="setUp" finished-at="2022-10-17T17:10:56 AMT" duration-ms="1823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="CreditAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_4_Credit_Positive_Test@8519cb4]" started-at="2022-10-17T17:10:56 AMT" name="CreditAPIValidateStatusCod" finished-at="2022-10-17T17:10:56 AMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateStatusCod -->
        <test-method signature="CreditAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_4_Credit_Positive_Test@8519cb4]" started-at="2022-10-17T17:10:56 AMT" name="CreditAPIValidatePositiveResponse" finished-at="2022-10-17T17:10:56 AMT" depends-on-methods="testCases.IqSoft_API_4_Credit_Positive_Test.CreditAPIValidateStatusCod" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidatePositiveResponse -->
      </class> <!-- testCases.IqSoft_API_4_Credit_Positive_Test -->
      <class name="testCases.IqSoft_API_3_GetBalance_Negative_Test">
        <test-method signature="GetBalanceAPIValidateResponseWithExpiredToken()[pri:1, instance:testCases.IqSoft_API_3_GetBalance_Negative_Test@72cc7e6f]" started-at="2022-10-17T17:11:12 AMT" name="GetBalanceAPIValidateResponseWithExpiredToken" finished-at="2022-10-17T17:11:13 AMT" duration-ms="851" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithExpiredToken(IqSoft_API_3_GetBalance_Negative_Test.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetBalanceAPIValidateResponseWithExpiredToken -->
        <test-method signature="GetBalanceAPIValidateResponseWithInvalidToken()[pri:2, instance:testCases.IqSoft_API_3_GetBalance_Negative_Test@72cc7e6f]" started-at="2022-10-17T17:11:13 AMT" name="GetBalanceAPIValidateResponseWithInvalidToken" finished-at="2022-10-17T17:11:14 AMT" duration-ms="754" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetBalanceAPIValidateResponseWithInvalidToken -->
        <test-method signature="GetBalanceAPIValidateResponseWithInvalidCurrencyID()[pri:3, instance:testCases.IqSoft_API_3_GetBalance_Negative_Test@72cc7e6f]" started-at="2022-10-17T17:11:14 AMT" name="GetBalanceAPIValidateResponseWithInvalidCurrencyID" finished-at="2022-10-17T17:11:14 AMT" duration-ms="505" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [20] but found [0],
Error Description: null expected [CurrencyNotExists] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [20] but found [0],
Error Description: null expected [CurrencyNotExists] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetBalanceAPIValidateResponseWithInvalidCurrencyID -->
        <test-method signature="GetBalanceAPIValidateResponseWithOtherCurrencyID()[pri:4, instance:testCases.IqSoft_API_3_GetBalance_Negative_Test@72cc7e6f]" started-at="2022-10-17T17:11:14 AMT" name="GetBalanceAPIValidateResponseWithOtherCurrencyID" finished-at="2022-10-17T17:11:16 AMT" duration-ms="1297" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[balanceUSD VS balanceEUR did not expect [9481.7] but found [9481.7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: balanceUSD VS balanceEUR did not expect [9481.7] but found [9481.7]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithOtherCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:113)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetBalanceAPIValidateResponseWithOtherCurrencyID -->
      </class> <!-- testCases.IqSoft_API_3_GetBalance_Negative_Test -->
      <class name="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test@2d901eb0]" started-at="2022-10-17T17:10:58 AMT" name="setUp" finished-at="2022-10-17T17:11:02 AMT" duration-ms="4021" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="RollBackAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test@2d901eb0]" started-at="2022-10-17T17:11:02 AMT" name="RollBackAPIValidateStatusCod" finished-at="2022-10-17T17:11:02 AMT" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateStatusCod -->
        <test-method signature="RollBackAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test@2d901eb0]" started-at="2022-10-17T17:11:02 AMT" name="RollBackAPIValidatePositiveResponse" finished-at="2022-10-17T17:11:02 AMT" depends-on-methods="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test.RollBackAPIValidateStatusCod" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidatePositiveResponse -->
        <test-method signature="RollBackAPIValidatePositiveResponseBalanceCorrection()[pri:3, instance:testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test@2d901eb0]" started-at="2022-10-17T17:11:02 AMT" name="RollBackAPIValidatePositiveResponseBalanceCorrection" finished-at="2022-10-17T17:11:02 AMT" depends-on-methods="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test.RollBackAPIValidateStatusCod" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidatePositiveResponseBalanceCorrection -->
      </class> <!-- testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test -->
      <class name="testCases.IqSoft_API_4_Credit_Negative_Test">
        <test-method signature="CreditAPIValidateResponseWithExpiredToken()[pri:1, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:16 AMT" name="CreditAPIValidateResponseWithExpiredToken" finished-at="2022-10-17T17:11:18 AMT" duration-ms="1852" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null],
amountBeforeCredit = amountAfterCredit: 9481.7 = 9480.7 expected [9480.7] but found [9481.7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null],
amountBeforeCredit = amountAfterCredit: 9481.7 = 9480.7 expected [9480.7] but found [9481.7]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithExpiredToken(IqSoft_API_4_Credit_Negative_Test.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithExpiredToken -->
        <test-method signature="CreditAPIValidateResponseWithInvalidToken()[pri:2, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:18 AMT" name="CreditAPIValidateResponseWithInvalidToken" finished-at="2022-10-17T17:11:19 AMT" duration-ms="1728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidToken -->
        <test-method signature="CreditAPIValidateResponseWithInvalidProductID()[pri:3, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:19 AMT" name="CreditAPIValidateResponseWithInvalidProductID" finished-at="2022-10-17T17:11:21 AMT" duration-ms="1539" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidProductID(IqSoft_API_4_Credit_Negative_Test.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidProductID -->
        <test-method signature="CreditAPIValidateResponseUsingTransactionIDTwice()[pri:4, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:21 AMT" name="CreditAPIValidateResponseUsingTransactionIDTwice" finished-at="2022-10-17T17:11:24 AMT" duration-ms="3420" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseUsingTransactionIDTwice -->
        <test-method signature="CreditAPIValidateResponseUsingAmountHigherThenBalance()[pri:5, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:24 AMT" name="CreditAPIValidateResponseUsingAmountHigherThenBalance" finished-at="2022-10-17T17:11:26 AMT" duration-ms="1949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseUsingAmountHigherThenBalance -->
        <test-method signature="CreditAPIValidateResponseWithInvalidAmount(double)[pri:6, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:26 AMT" name="CreditAPIValidateResponseWithInvalidAmount" data-provider="invalidAmountData" finished-at="2022-10-17T17:11:29 AMT" duration-ms="3038" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[0.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidAmount -->
        <test-method signature="CreditAPIValidateResponseWithInvalidAmount(double)[pri:6, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:29 AMT" name="CreditAPIValidateResponseWithInvalidAmount" data-provider="invalidAmountData" finished-at="2022-10-17T17:11:31 AMT" duration-ms="1732" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidAmount -->
        <test-method signature="CreditAPIValidateResponseWithInvalidAmount(double)[pri:6, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:31 AMT" name="CreditAPIValidateResponseWithInvalidAmount" data-provider="invalidAmountData" finished-at="2022-10-17T17:11:33 AMT" duration-ms="1798" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidAmount -->
        <test-method signature="CreditAPIValidateResponseWithInvalidAmount(double)[pri:6, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:33 AMT" name="CreditAPIValidateResponseWithInvalidAmount" data-provider="invalidAmountData" finished-at="2022-10-17T17:11:35 AMT" duration-ms="1906" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.05]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidAmount -->
        <test-method signature="CreditAPIValidateResponseWithInvalidAmount(double)[pri:6, instance:testCases.IqSoft_API_4_Credit_Negative_Test@5afa3c9]" started-at="2022-10-17T17:11:35 AMT" name="CreditAPIValidateResponseWithInvalidAmount" data-provider="invalidAmountData" finished-at="2022-10-17T17:11:37 AMT" duration-ms="1923" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1.005]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditAPIValidateResponseWithInvalidAmount -->
      </class> <!-- testCases.IqSoft_API_4_Credit_Negative_Test -->
      <class name="testCases.IqSoft_API_6_RollBackDebit_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_6_RollBackDebit_Positive_Test@3f191845]" started-at="2022-10-17T17:11:05 AMT" name="setUp" finished-at="2022-10-17T17:11:10 AMT" duration-ms="4414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="RollBackAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_6_RollBackDebit_Positive_Test@3f191845]" started-at="2022-10-17T17:11:10 AMT" name="RollBackAPIValidateStatusCod" finished-at="2022-10-17T17:11:10 AMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateStatusCod -->
        <test-method signature="RollBackAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_6_RollBackDebit_Positive_Test@3f191845]" started-at="2022-10-17T17:11:10 AMT" name="RollBackAPIValidatePositiveResponse" finished-at="2022-10-17T17:11:10 AMT" depends-on-methods="testCases.IqSoft_API_6_RollBackDebit_Positive_Test.RollBackAPIValidateStatusCod" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidatePositiveResponse -->
        <test-method signature="RollBackAPIValidatePositiveResponseBalanceCorrection()[pri:3, instance:testCases.IqSoft_API_6_RollBackDebit_Positive_Test@3f191845]" started-at="2022-10-17T17:11:10 AMT" name="RollBackAPIValidatePositiveResponseBalanceCorrection" finished-at="2022-10-17T17:11:10 AMT" depends-on-methods="testCases.IqSoft_API_6_RollBackDebit_Positive_Test.RollBackAPIValidateStatusCod" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidatePositiveResponseBalanceCorrection -->
      </class> <!-- testCases.IqSoft_API_6_RollBackDebit_Positive_Test -->
      <class name="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test@3ba987b8]" started-at="2022-10-17T17:11:02 AMT" name="setUp" finished-at="2022-10-17T17:11:05 AMT" duration-ms="3045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="RollBackAPIValidateStatusCod()[pri:1, instance:testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test@3ba987b8]" started-at="2022-10-17T17:11:05 AMT" name="RollBackAPIValidateStatusCod" finished-at="2022-10-17T17:11:05 AMT" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidateStatusCod -->
        <test-method signature="RollBackAPIValidatePositiveResponse()[pri:2, instance:testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test@3ba987b8]" started-at="2022-10-17T17:11:05 AMT" name="RollBackAPIValidatePositiveResponse" finished-at="2022-10-17T17:11:05 AMT" depends-on-methods="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test.RollBackAPIValidateStatusCod" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidatePositiveResponse -->
        <test-method signature="RollBackAPIValidatePositiveResponseBalanceCorrection()[pri:3, instance:testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test@3ba987b8]" started-at="2022-10-17T17:11:05 AMT" name="RollBackAPIValidatePositiveResponseBalanceCorrection" finished-at="2022-10-17T17:11:05 AMT" depends-on-methods="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test.RollBackAPIValidateStatusCod" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RollBackAPIValidatePositiveResponseBalanceCorrection -->
      </class> <!-- testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test -->
    </test> <!-- API Integration Automation Test -->
  </suite> <!-- IQsoft API Integration -->
</testng-results>
